# Generated by Django 4.0.1 on 2022-05-26 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ad_options_alter_comment_options_ad_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
    ]
