# Generated by Django 4.0.1 on 2022-05-26 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_remove_ad_created_at_remove_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
