# Generated by Django 4.0.1 on 2022-06-03 09:45

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Имя пользователя')),
                ('last_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Фамилия пользователя')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Телефон пользователя')),
                ('email', models.EmailField(max_length=120, null=True, unique=True, verbose_name='Электронный адрес пользователя')),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('admin', 'Администратор')], default='user', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
